### ISSUE TITLE
Publish the repo

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/xcub-moveit2#22]
We want to make this repository public and announce its existence on our main channels.

```[tasklist]
### Tasks
- [x] Change the name of the repo
- [x] Make it public
- [x] Announce in `community`
- [x] Announce in `robotics-knowledgebase-iit`
- [x] Announce it internally
- [x] Add it to the MoveIt website
```

**Comment by martinaxgloria** [comment]
Hi @traversaro, 
as per https://github.com/icub-tech-iit/tickets/issues/218, the last step to accomplish this task is to publish the iCub/ergoCub support on the MoveIt website. Are you in contact with some maintainers to understand how to proceed? 

cc @Nicogene @pattacini

**Comment by traversaro** [comment]
> Hi @traversaro,
> as per [icub-tech-iit/tickets#218](https://github.com/icub-tech-iit/tickets/issues/218), the last step to accomplish this task is to publish the iCub/ergoCub support on the MoveIt website. Are you in contact with some maintainers to understand how to proceed?

In https://moveit.ros.org/robots/ they mentioned to either contact picknik or post on discourse. To understand more, I asked on MoveIt's Discord: https://discordapp.com/channels/717058325480734830/717148778238574623/1185146323687710791 . I will ping relevant persons if we do not get an answer. In the meanwhile, I would prepare a cool photo to replace the really old one in the moveit website.

**Comment by Nicogene** [comment]
> > Hi @traversaro,
> > as per [icub-tech-iit/tickets#218](https://github.com/icub-tech-iit/tickets/issues/218), the last step to accomplish this task is to publish the iCub/ergoCub support on the MoveIt website. Are you in contact with some maintainers to understand how to proceed?
> 
> In [moveit.ros.org/robots](https://moveit.ros.org/robots/) they mentioned to either contact picknik or post on discourse. To understand more, I asked on MoveIt's Discord: [discordapp.com/channels/717058325480734830/717148778238574623/1185146323687710791](https://discordapp.com/channels/717058325480734830/717148778238574623/1185146323687710791) . I will ping relevant persons if we do not get an answer. In the meanwhile, I would prepare a cool photo to replace the really old one in the moveit website.

We should add both iCub and ergoCub to the website, for the right photo to put we may ask @maggia80

**Comment by traversaro** [comment]
> > Hi @traversaro,
> > as per [icub-tech-iit/tickets#218](https://github.com/icub-tech-iit/tickets/issues/218), the last step to accomplish this task is to publish the iCub/ergoCub support on the MoveIt website. Are you in contact with some maintainers to understand how to proceed?
> 
> In https://moveit.ros.org/robots/ they mentioned to either contact picknik or post on discourse. To understand more, I asked on MoveIt's Discord: https://discordapp.com/channels/717058325480734830/717148778238574623/1185146323687710791 . I will ping relevant persons if we do not get an answer. In the meanwhile, I would prepare a cool photo to replace the really old one in the moveit website.

On MoveIt's discord @sea-bass kindly pointed out that we can just open a PR against this repo: https://github.com/ros-planning/moveit.ros.org/blob/789f50461b68b332b02695e3cb2976db3df0b5c7/robots/index.markdown?plain=1#L1594-L1603 , so probably we can just open a PR on that repo.

**Comment by maggia80** [comment]
![image](https://github.com/icub-tech-iit/xcub-moveit2/assets/6987330/f4a9a1ca-b462-48bd-87e0-20adbab64ba3)
![P058324-119830](https://github.com/icub-tech-iit/xcub-moveit2/assets/6987330/e3b90f71-e310-4dcd-9e61-8e1de04cce31)


![P058324-463960](https://github.com/icub-tech-iit/xcub-moveit2/assets/6987330/e267791a-de7c-4679-9e07-2d53e61e66e3)

**Comment by martinaxgloria** [comment]
Ok, thank you @traversaro! I'll open a PR.

**Comment by martinaxgloria** [comment]
PR opened here:

- https://github.com/ros-planning/moveit.ros.org/pull/832

cc @Nicogene @pattacini @maggia80 @traversaro

**Comment by martinaxgloria** [comment]
PR merged. Now, you can find iCub and ergoCub within [robots page](https://moveit.ros.org/robots/) on MoveIt website! :rocket: 

cc @Nicogene @pattacini @maggia80 @traversaro

**Comment by pattacini** [comment]
Superb! 🏆

**Comment by maggia80** [comment]
Awesome!
