### ISSUE TITLE
MoveIt2 MVP – (MoM meeting 31 Aug 2023)

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/xcub-moveit2#7]
## Participants
@martinaxgloria @Nicogene @traversaro @pattacini 

## Discussion

```[tasklist]
### MVP
- [x] Cartesian control of `one arm`.
- [x] Cartesian control of `one arm + torso` (to extend iCub reachability).
- [x] Cartesian control works w/ `position-direct`, therefore we need to envisage a way to choose control mode as well.
- [ ] If possible fiddle w/ the existing moveIT! 2 plugins for collision avoidance during the motion planning
- [x] Test cartesian control on the physical robot
- [x] Port the work on ergoCub
```

### Installation
- @traversaro aims to incorporate the installation of the main components using the superbuild. To this end, we need releases of https://github.com/robotology/yarp-devices-ros2.
- We're required to finalize the documentation.
- We could explore providing a minimal colcon-based installation for non-icub users.

### ergoCub
- @martinaxgloria reported that extending MoveIt2 to ergoCub is doable.

### URDF
- The idea is to reduce the number of URDF required to cover the family of iCub and simulated robots as much as possible. Probably, we could get away with just one URDF. To be checked.
- `YARP_ROBOTNAME` should be used to pick the name of the robot under use.

### Open points to explore
- Do we need the ROS-based bridge between MoveIt2 and gazebo/robot? Alternatively, MoveIt2 plugins may call directly YARP serices.
- Does `position-direct` rely on topics (streaming) rather than services (rpc)?

### Upstream contributions
- Once this repo will be made public, we could advertise it from within MoveIt2 main website.

```[tasklist]
### Tasks
```

**Comment by traversaro** [comment]
> @traversaro aims to incorporate the installation of the main components using the superbuild. To this end, we need releases of https://github.com/robotology/yarp-devices-ros2.

yarp-devices-ros2 was released (see https://github.com/robotology/yarp-devices-ros2/releases/tag/v1.0.0), so we can now proceed, see https://github.com/robotology/robotology-superbuild/ .
